# SPDX-FileCopyrightText: 2025-2026 NORCE Research AS
# SPDX-License-Identifier: GPL-3.0
# pylint: disable=R0914

"""
Test on a complex model with a segmented well and faults.
The model is a modified sector from the Drogon data set:
https://github.com/OPM/opm-tests/tree/master/drogon/model/DROGON_HIST

This is generated by using pycopm and executing:
pycopm -i DROGON_HIST.DATA -o . -v 'opernum 2' -p 4 -l SECTOR -w MODEL3

and by following the steps for the different sections for the deck in:
https://cssr-tools.github.io/pycopm/examples.html#drogon

The added opernum in the REGIONS section corresponds to:
OPERNUM
104098*1 /
EQUALS
OPERNUM 2 30 38 47 52 2* /
/
"""

from pathlib import Path
import subprocess
import numpy as np
from opm.io.ecl import EclFile as OpmFile
from opm.io.ecl import ERst as OpmRestart


def test_6_segwell_faults(flow, tmp_path, monkeypatch):
    """See examples/decks/MODEL3.DATA"""
    repo_root = Path(__file__).parents[1]
    monkeypatch.chdir(tmp_path)
    subprocess.run(
        [
            flow,
            f"{repo_root}/examples/decks/MODEL3.DATA",
            f"--output-dir={tmp_path}/reference",
        ],
        check=True,
    )
    subprocess.run(
        [
            "pycopm",
            "-i",
            f"{repo_root}/examples/decks/MODEL3.DATA",
            "-f",
            flow,
            "-x",
            "0,2,0,2,0,0,0,0,0,0",
            "-z",
            "0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,0,2,2,2,0",
            "-w",
            "COARSER",
            "-l",
            "C0",
            "-p",
            "1",
            "-q",
            "1",
            "-a",
            "max",
            "-m",
            "all",
        ],
        check=True,
    )
    assert (tmp_path / "COARSER.INIT").is_file()
    assert (tmp_path / "COARSER.EGRID").is_file()
    subprocess.run(
        [
            flow,
            "COARSER.DATA",
            f"--output-dir={tmp_path}/coarser",
        ],
        check=True,
    )
    bini = OpmFile("reference/MODEL3.INIT")
    cini = OpmFile("coarser/COARSER.INIT")
    bpv = np.array(bini["PORV"])
    cpv = np.array(cini["PORV"])
    assert abs(np.sum(bpv) - np.sum(cpv)) < 50  # ca. 4.61992e8 porv in the ref
    assert np.sum(cpv > 0) == 255
    brst = OpmRestart("reference/MODEL3.UNRST")
    crst = OpmRestart("coarser/COARSER.UNRST")
    bgf = np.array(brst["FIPGAS", 0])
    cgf = np.array(crst["FIPGAS", 0])
    assert abs(np.sum(bgf) - np.sum(cgf)) < 50  # ca. 2.56191e10 fipgas in the ref
    for sub in ["0", "1"]:
        subprocess.run(
            [
                "pycopm",
                "-i",
                f"{repo_root}/examples/decks/MODEL3.DATA",
                "-g",
                "2,2,2",
                "-f",
                flow,
                "-w",
                f"FINER{sub}",
                "-l",
                f"R0{sub}",
                "-q",
                "1",
                "-m",
                "all",
                "-explicit",
                sub,
            ],
            check=True,
        )
        assert (tmp_path / f"FINER{sub}.INIT").is_file()
        assert (tmp_path / f"FINER{sub}.EGRID").is_file()
        subprocess.run(
            [
                flow,
                f"FINER{sub}.DATA",
                "--output-dir=finer",
            ],
            check=True,
        )
        rini = OpmFile(f"finer/FINER{sub}.INIT")
        rpv = np.array(rini["PORV"])
        assert abs(np.sum(bpv) - np.sum(rpv)) < 50  # ca. 4.61992e8 porv in the ref
        assert np.sum(rpv > 0) == 22896
        rrst = OpmRestart(f"finer/FINER{sub}.UNRST")
        rgf = np.array(rrst["FIPGAS", 0])
        assert abs(np.sum(bgf) - np.sum(rgf)) < 50  # ca. 2.56191e10 fipgas in the ref
    for i, val in enumerate(
        ["diamond 0", "diamond 1", "diamondxy 3", "box [-3,2] [-1,1] [-1,2]"]
    ):
        subprocess.run(
            [
                "pycopm",
                "-i",
                f"{repo_root}/examples/decks/MODEL3.DATA",
                "-v",
                f"A4 {val}",
                "-f",
                flow,
                "-w",
                f"SUBMODEL{i}",
                "-l",
                f"S{i}",
                "-p",
                f"{[1,3,3,4][i]}",
                "-m",
                "deck_dry",
            ],
            check=True,
        )
        assert (tmp_path / f"SUBMODEL{i}.INIT").is_file()
        assert (tmp_path / f"SUBMODEL{i}.EGRID").is_file()
        bini = OpmFile("reference/MODEL3.INIT")
        cini = OpmFile(f"SUBMODEL{i}.INIT")
        bpv = np.array(bini["PORV"])
        cpv = np.array(cini["PORV"])
        assert abs(np.sum(bpv) - np.sum(cpv)) < 1  # ca. 4.61992e8 porv in the ref
        assert np.sum(cpv > 0) == [20, 77, 731, 260][i]
