# SPDX-FileCopyrightText: 2024-2026 NORCE Research AS
# SPDX-License-Identifier: GPL-3.0
# pylint: disable=R0913,R0914,R0916,R0917

"""Write OPM Flow decks, corner-point grids, properties, and ERT files."""

import shlex
from pathlib import Path
from typing import Any

import numpy as np
from mako.template import Template
from numpy.typing import NDArray
from opm.io.ecl import EclFile as OpmFile

from pycopm.config.config import ConfigViaDeck, ConfigViaTOML

HEADER = (
    "-- Copyright (C) 2024-2026 NORCE Research AS\n"
    "-- This deck was generated by pycopm https://github.com/cssr-tools/pycopm\n"
)


def format_opm_compact_values(v: NDArray) -> list[str]:
    """Convert values to OPM repeated-value notation.

    Parameters
    ----------
    v
        One-dimensional values to compact.

    Returns
    -------
    list[str]
        Values formatted as ``n*value`` where consecutive values repeat."""
    v = np.array(v)
    change_idx = np.flatnonzero(np.diff(v, prepend=v[0] - 1))
    counts = np.diff(np.append(change_idx, v.size))
    vals = v[change_idx]

    out = []
    for val, n in zip(vals, counts):
        val_str = str(int(val)) if float(val).is_integer() else str(val)
        out.append(f"{n}*{val_str} " if n > 1 else f"{val_str} ")
    return out


def round_like_e(
    values: NDArray | list,
    significant_digits: int,
) -> NDArray:
    """Round values to a number of significant digits.

    Parameters
    ----------
    values
        Values to round.
    significant_digits
        Number of significant digits, or zero to preserve machine precision.

    Returns
    -------
    NDArray
        Rounded values with the original shape."""
    if significant_digits == 0:
        return np.asarray(values)
    values = np.asarray(values)
    decimal_digits = significant_digits - 1
    rounded_values = np.fromiter(
        (float(f"{value:.{decimal_digits}E}") for value in values.flat),
        dtype=float,
        count=values.size,
    )
    return rounded_values.reshape(values.shape)


def _identify_removed_pillars(cfg: ConfigViaTOML) -> tuple[NDArray, NDArray]:
    """Find COORD and ZCORN indices removed by TOML coarsening.

    Parameters
    ----------
    cfg
        TOML configuration containing axis coarsening arrays.

    Returns
    -------
    coord_indices, zcorn_indices
        Indices to remove from the reference grid arrays."""
    mr: list[float] = []
    ir: list[float] = []
    nx_fine, ny_fine, nz_fine = cfg.original_nx, cfg.original_ny, cfg.original_nz
    nxyz = cfg.original_cell_count
    for column_index in range(nx_fine + 1):
        if cfg.x_coarsening[column_index] > 1:
            for pillar_index in range(
                column_index, (nx_fine + 1) * (ny_fine + 1), nx_fine + 1
            ):
                mr.extend(range(pillar_index * 6, pillar_index * 6 + 6))
            for zcorn_index in range(2 * column_index - 1, 8 * nxyz, 2 * nx_fine):
                ir.extend([zcorn_index, zcorn_index + 1])
    for row_index in range(ny_fine + 1):
        if cfg.y_coarsening[row_index] > 1:
            pillar_start = row_index * (nx_fine + 1)
            pillar_stop = (row_index + 1) * (nx_fine + 1)
            for pillar_index in range(pillar_start, pillar_stop):
                mr.extend(range(pillar_index * 6, pillar_index * 6 + 6))
            for zcorn_index in range(
                (2 * row_index - 1) * 2 * nx_fine,
                8 * nxyz,
                4 * nx_fine * ny_fine,
            ):
                ir.extend(range(zcorn_index, zcorn_index + 4 * nx_fine))
    layer_size = 4 * nx_fine * ny_fine
    for layer_index in range(nz_fine + 1):
        if cfg.z_coarsening[layer_index] > 1:
            start_index = (2 * layer_index - 1) * layer_size
            stop_index = (2 * layer_index + 1) * layer_size
            ir.extend(range(start_index, stop_index))
    return np.asarray(mr, dtype=int), np.asarray(ir, dtype=int)


def _render_template(template_path: Path, output_path: Path, **variables: Any) -> None:
    """Render a Mako template to a UTF-8 file.

    Parameters
    ----------
    template_path
        Source template path.
    output_path
        Destination path.
    **variables
        Values passed to the template."""
    template = Template(filename=str(template_path))
    output_path.write_text(template.render(**variables), encoding="utf8")


def write_coarsened_model_files(cfg: ConfigViaTOML, number_tables: int) -> None:
    """Write grid, deck, schedule, job, observation, and ERT files.

    Parameters
    ----------
    cfg
        TOML configuration for the generated project.
    number_tables
        Number of saturation-function tables to generate."""
    if cfg.saturation_function_method > 0:
        _write_let_tables(cfg, number_tables)
    _write_grid_files(cfg)
    _write_ert_files(cfg, number_tables)
    project_path = Path(cfg.output_directory)
    template_path = Path(cfg.resource_directory) / "template_scripts"
    variables = {
        "original_to_output_i": cfg.original_to_output_i,
        "original_to_output_j": cfg.original_to_output_j,
        "original_to_output_k": cfg.original_to_output_k,
    }
    _render_template(
        template_path / cfg.model_name / "schedule.mako",
        project_path / "preprocessing" / "schedule.SCH",
        **variables,
    )
    _render_template(
        template_path / "common" / "time_eval.mako",
        project_path / "jobs" / "time_eval.py",
        name=cfg.reference_case_name,
    )
    _render_template(
        template_path / "common" / "flow_eval.mako",
        project_path / "jobs" / "flow_eval.py",
        flow=shlex.split(cfg.flow_command.strip())
        + [f"{cfg.reference_case_name}_COARSER.DATA"],
    )
    _render_template(
        template_path / cfg.model_name / "deck.mako",
        project_path / "preprocessing" / f"{cfg.reference_case_name}_COARSER.DATA",
        output_nx=cfg.output_nx,
        output_ny=cfg.output_ny,
        output_nz=cfg.output_nz,
        output_directory=cfg.output_directory,
        rock_property_settings=cfg.rock_property_settings,
        execution_mode=cfg.execution_mode,
        saturation_function_method=cfg.saturation_function_method,
        use_let_tables=cfg.use_let_tables,
        initial=cfg.initialization_method,
        original_to_output_k=cfg.original_to_output_k,
        number_tables=number_tables,
    )


def _write_ert_files(cfg: ConfigViaTOML, number_tables: int) -> None:
    """Write the ERT configuration, parameter, job, and observation files."""
    project_path = Path(cfg.output_directory)
    template_path = Path(cfg.resource_directory) / "template_scripts"
    for coefficient_index, coefficient in enumerate(cfg.let_parameters):
        if (
            coefficient[2] == 1
            and cfg.execution_mode in ("files", "ert")
            and cfg.saturation_function_method == 1
        ):
            cfg.use_let_tables = True
            variables = {
                "i": coefficient_index,
                "number_tables": number_tables,
                "let_parameters": cfg.let_parameters,
            }
            coefficient_name = str(coefficient[0])
            _render_template(
                template_path / "common" / "let.mako",
                project_path / "parameters" / f"coeff_{coefficient_name}.tmpl",
                **variables,
            )
            _render_template(
                template_path / "common" / "let_priors.mako",
                project_path / "parameters" / f"coeff_{coefficient_name}_priors.data",
                **variables,
            )
    _render_template(
        template_path / cfg.model_name / "observations.mako",
        project_path / "observations" / "observations.data",
        minerror=cfg.observation_minimum_errors,
        error=cfg.observation_relative_errors,
    )
    variables = {
        "let_parameters": cfg.let_parameters,
        "execution_mode": cfg.execution_mode,
        "number_tables": number_tables,
    }
    if cfg.use_let_tables:
        _render_template(
            template_path / cfg.model_name / "table_eval.mako",
            project_path / "jobs" / "table_eval.py",
            **variables,
        )
    _render_template(
        template_path / "common" / "ert.mako",
        project_path / "ert.ert",
        execution_mode=cfg.execution_mode,
        ensemble_size=cfg.ensemble_size,
        min_successful_realizations=cfg.min_successful_realizations,
        max_realization_runtime_seconds=cfg.max_realization_runtime_seconds,
        max_parallel_realizations=cfg.max_parallel_realizations,
        random_seed=cfg.random_seed,
        reference_case_name=cfg.reference_case_name,
        rock_property_settings=cfg.rock_property_settings,
        use_let_tables=cfg.use_let_tables,
        let_parameters=cfg.let_parameters,
        resource_directory=cfg.resource_directory,
        model_name=cfg.model_name,
        number_tables=number_tables,
    )


def _write_let_tables(cfg: ConfigViaTOML, number_tables: int) -> None:
    """Write the LET saturation-function tables."""
    table_lines = [HEADER]

    if cfg.model_name == "norne":
        table_lines.append("SWOFLET\n")
        for _ in range(number_tables):
            table_lines.append(
                f"0 0.0001 {max(1.1, cfg.let_parameters[0][1])} "
                f"{10.0 ** cfg.let_parameters[1][1]} {max(1.1, cfg.let_parameters[2][1])} "
                "0.5 0 0 "
                f"{max(1.0, cfg.let_parameters[12][1]) * max(1.1, cfg.let_parameters[3][1])} "
                f"{10.0 ** cfg.let_parameters[4][1]} {max(1.1, cfg.let_parameters[5][1])} "
                "1 0.69977 17.56167 0.95615 3.76138 0.03819 /\n"
            )
        for _ in range(number_tables):
            table_lines.append(
                f"0 0.0001 {max(1.1, cfg.let_parameters[0][1])} "
                f"{10.0 ** cfg.let_parameters[1][1]} {max(1.1, cfg.let_parameters[2][1])} "
                f"0.5 0 0 {max(1.1, cfg.let_parameters[3][1])} "
                f"{max(0.9, cfg.let_parameters[13][1]) * 10.0 ** cfg.let_parameters[4][1]} "
                f"{max(1.0, cfg.let_parameters[14][1]) * max(1.1, cfg.let_parameters[5][1])} "
                "1 0.69977 17.56167 0.95615 3.76138 0.03819 /\n"
            )

        table_lines.append("SGOFLET\n")
        for _ in range(number_tables):
            table_lines.append(
                f"0 0 {max(1.0, cfg.let_parameters[15][1]) * max(1.1, cfg.let_parameters[6][1])} "
                f"{10.0 ** cfg.let_parameters[7][1]} {max(1.1, cfg.let_parameters[8][1])} "
                f"0.95 0 0.0001 {max(1.1, cfg.let_parameters[9][1])} "
                f"{10.0 ** cfg.let_parameters[10][1]} {max(1.1, cfg.let_parameters[11][1])} "
                "0.99997432 1 1 1 0 0 /\n"
            )
        for _ in range(number_tables):
            table_lines.append(
                f"0 0 {max(1.1, cfg.let_parameters[6][1])} "
                f"{max(1.0, cfg.let_parameters[16][1]) * 10.0 ** cfg.let_parameters[7][1]} "
                f"{max(1.0, cfg.let_parameters[17][1]) * max(1.1, cfg.let_parameters[8][1])} "
                f"0.95 0 0.0001 {max(1.1, cfg.let_parameters[9][1])} "
                f"{10.0 ** cfg.let_parameters[10][1]} {max(1.1, cfg.let_parameters[11][1])} "
                "0.99997432 1 1 1 0 0 /\n"
            )

    elif cfg.model_name == "drogon":
        table_lines.append("SWOFLET\n")
        for _ in range(number_tables):
            table_lines.append(
                f"0 0.0001 {max(1.1, cfg.let_parameters[0][1])} "
                f"{10.0 ** cfg.let_parameters[1][1]} {max(1.1, cfg.let_parameters[2][1])} "
                f"{cfg.let_parameters[14][1]} 0 0 "
                f"{max(1.0, cfg.let_parameters[12][1]) * max(1.1, cfg.let_parameters[3][1])} "
                f"{10.0 ** cfg.let_parameters[4][1]} {max(1.1, cfg.let_parameters[5][1])} "
                f"{cfg.let_parameters[15][1]} 0.69977 17.56167 0.95615 3.76138 0.03819 /\n"
            )

        table_lines.append("SGOFLET\n")
        for _ in range(number_tables):
            table_lines.append(
                f"0 0 {max(1.0, cfg.let_parameters[13][1]) * max(1.1, cfg.let_parameters[6][1])} "
                f"{10.0 ** cfg.let_parameters[7][1]} {max(1.1, cfg.let_parameters[8][1])} "
                f"{cfg.let_parameters[16][1]} 0 0.0001 {max(1.1, cfg.let_parameters[9][1])} "
                f"{10.0 ** cfg.let_parameters[10][1]} {max(1.1, cfg.let_parameters[11][1])} "
                f"{cfg.let_parameters[17][1]} 1 1 1 0 0 /\n"
            )

    (Path(cfg.output_directory) / "preprocessing" / "tables.inc").write_text(
        "".join(table_lines), encoding="utf8"
    )


def _write_grid_files(cfg: ConfigViaTOML) -> None:
    """Write the OPM grid-related files."""
    case = (
        Path(cfg.resource_directory)
        / "reference_simulation"
        / cfg.model_name
        / cfg.reference_case_name
    )
    grid_path = f"{case}.EGRID"
    grid_file = OpmFile(grid_path)
    zc, cr = grid_file["ZCORN"], grid_file["COORD"]
    coord_indices, zcorn_indices = _identify_removed_pillars(cfg)
    cr = np.delete(np.asarray(cr), coord_indices)
    zc = np.delete(np.asarray(zc), zcorn_indices)
    write_grid(cfg, cr, zc, False)
    project_path = Path(cfg.output_directory)
    template_path = Path(cfg.resource_directory) / "template_scripts" / cfg.model_name
    variables = {
        "original_to_output_i": cfg.original_to_output_i,
        "original_to_output_j": cfg.original_to_output_j,
        "original_to_output_k": cfg.original_to_output_k,
    }
    _render_template(
        template_path / "fault.mako",
        project_path / "preprocessing" / "fault.inc",
        **variables,
    )
    if cfg.model_name == "norne":
        _render_template(
            template_path / "localbarriers.mako",
            project_path / "preprocessing" / "localbarriers.inc",
            **variables,
        )
    elif cfg.model_name == "drogon":
        _render_template(
            template_path / "trans.mako",
            project_path / "preprocessing" / "trans.inc",
            **variables,
        )


def write_include(output_path: Path, text: str) -> None:
    """Write text to an OPM include file with the pycopm header.

    Parameters
    ----------
    output_path
        Destination include path.
    text
        OPM deck text written after the header."""
    output_path.write_text(f"{HEADER}{text}", encoding="utf8")


def write_property(output_path: Path, keyword: str, values: NDArray, num_dig) -> None:
    """Write one compact OPM property.

    Parameters
    ----------
    output_path
        Destination include path.
    keyword
        OPM property keyword.
    values
        Property values in global-cell order.
    num_dig
        Number of significant digits."""
    compacted_values = format_opm_compact_values(
        round_like_e(np.asarray(values), num_dig)
    )
    output_path.write_text(
        f"{HEADER}{keyword}\n{''.join(compacted_values)}/\n", encoding="utf8"
    )


def write_compact_property_file(
    preprocessing_path: Path, property_name: str, values: NDArray, num_dig
) -> None:
    """Write one compacted OPM property to a file."""
    write_property(
        preprocessing_path / f"{property_name}.inc",
        property_name.upper(),
        values,
        num_dig,
    )


def write_porv(dck: ConfigViaDeck, modified_deck: list[str]) -> None:
    """Write the OPM grid-related files."""
    write_property_inc(
        dck,
        "porv",
        dck.output_porv,
        dck.output_porv.size,
        modified_deck,
        False,
    )


def write_property_inc(
    dck: ConfigViaDeck,
    property_name: str,
    property_values: NDArray,
    number_values: int,
    modified_deck: list[str],
    allow_inline: bool = False,
    file_suffix: str = "",
) -> bool:
    """Write a property include or inline a constant property.

    Parameters
    ----------
    dck
        Deck configuration controlling paths, prefixes, and precision.
    property_name
        OPM property name.
    property_values
        Values in output-grid order.
    number_values
        Expected number of output values.
    modified_deck
        Deck lines in which a constant property may be inlined.
    allow_inline
        Inline a property when all values are equal.
    file_suffix
        Optional suffix added before ``.INC``.

    Returns
    -------
    bool
        ``True`` when the property was inlined, otherwise ``False``."""
    output_directory = Path(dck.output_directory)
    num_dig = dck.significant_digits
    property_values = np.asarray(property_values)
    compacted_values = format_opm_compact_values(round_like_e(property_values, num_dig))
    property_path = output_directory / (
        f"{dck.include_prefix}{property_name.upper()}{file_suffix}.INC"
    )
    if (
        allow_inline
        and not file_suffix
        and compacted_values
        and len(compacted_values) == 1
        and "*" in compacted_values[0]
        and int(compacted_values[0].split("*", maxsplit=1)[0]) == number_values
    ):
        include_line = f"'{dck.include_prefix}{property_name.upper()}.INC' /\n"
        include_index = modified_deck.index(include_line)
        repeated_value = compacted_values[0].split("*", maxsplit=1)[1]
        del modified_deck[include_index]
        del modified_deck[include_index - 1]
        modified_deck.insert(
            include_index - 1,
            f"{property_name.upper()}\n{number_values}*{repeated_value}/\n",
        )
        property_path.unlink(missing_ok=True)
        return True
    property_path.write_text(
        HEADER + f"{property_name.upper()}\n{''.join(compacted_values)}/\n",
        encoding="utf8",
    )
    return False


def write_grid(
    cfg: ConfigViaDeck | ConfigViaTOML, cr: NDArray, zc: NDArray, dual: bool
) -> None:
    """Write a corner-point grid in GRDECL syntax.

    Parameters
    ----------
    cfg
        Deck or TOML configuration containing output dimensions and precision.
    cr, zc
        Flattened ``COORD`` and ``ZCORN`` arrays.
    dual
        Extend the j dimension for a dual-porosity grid."""
    if isinstance(cfg, ConfigViaDeck):
        cfg.output_cell_count = cfg.output_nx * cfg.output_ny * cfg.output_nz
    output_grid = [
        HEADER,
        "SPECGRID\n",
        f"{cfg.output_nx} {cfg.output_ny * (int(dual) + 1) + int(dual)} {cfg.output_nz} /\n",
        "COORD\n",
    ]
    num_dig = cfg.significant_digits
    output_grid.extend(format_opm_compact_values(round_like_e(np.asarray(cr), num_dig)))
    output_grid.extend(["/\n", "ZCORN\n"])
    output_grid.extend(format_opm_compact_values(round_like_e(np.asarray(zc), num_dig)))
    output_grid.append("/")
    if isinstance(cfg, ConfigViaDeck):
        if not cfg.dual_porosity_criterion and not cfg.grid_transformation:
            output_grid.append("\nACTNUM\n")
            output_grid.extend(
                format_opm_compact_values(
                    round_like_e(np.asarray(cfg.output_actnum), num_dig)
                )
            )
            output_grid.append("/")
        output_grid.append("\n")
        output_path = Path(cfg.output_directory) / f"{cfg.include_prefix}GRID.INC"
    else:
        output_grid.append("\n")
        output_path = (
            Path(cfg.output_directory)
            / "preprocessing"
            / f"{cfg.reference_case_name}_COARSER.GRDECL"
        )
    output_path.write_text("".join(output_grid), encoding="utf8")


def write_reference_to_coarse_map(dck: ConfigViaDeck, reftocoa: NDArray) -> None:
    """Write the reference-to-coarse mapping as OPERNUM.

    Parameters
    ----------
    dck
        Deck configuration controlling the output path and precision.
    reftocoa
        Coarse-cell identifier for every reference-grid cell."""
    num_dig = dck.significant_digits
    output_directory = Path(dck.output_directory)
    opernum_output = format_opm_compact_values(round_like_e(reftocoa, num_dig))
    opernum_path = (
        output_directory / f"{dck.original_deck_name}_OPERNUM_PYCOPM_REFTOCOA.INC"
    )
    opernum_path.write_text(
        f"{HEADER}OPERNUM\n{''.join(opernum_output)}/\n", encoding="utf8"
    )


def write_dual_properties(
    dck: ConfigViaDeck,
    coarsening,
    number_values: int,
    modified_deck: list[str],
) -> None:
    """Finalize property files for a dual-porosity grid.

    Parameters
    ----------
    dck
        Deck configuration and generated property names.
    coarsening
        Coarsening data containing matrix and fracture transmissibilities.
    number_values
        Number of cells in the extended dual grid.
    modified_deck
        Deck lines that may receive inlined properties."""
    names = (
        dck.props_keywords
        + dck.grids_keywords
        + dck.regions_keywords
        + dck.solution_keywords
        + ["porv"]
    )
    output_directory = Path(dck.output_directory)
    for property_name in names:
        property_path = output_directory / (
            f"{dck.include_prefix}{property_name.upper()}.INC"
        )
        if property_name not in ["tranx", "trany"]:
            temporary_property_path = output_directory / (
                f"{dck.include_prefix}{property_name.upper()}_DUAL_TMP_PYCOPM.INC"
            )
            if temporary_property_path.is_file():
                temporary_property_path.replace(property_path)
            continue
        property_values = (
            coarsening.coarse_tranx
            if property_name == "tranx"
            else coarsening.coarse_trany
        )
        write_property_inc(
            dck,
            property_name,
            property_values,
            number_values,
            modified_deck,
            True,
        )
